---
# tasks file for ansible_host_bootstrap

- name: Detect OS.
  ansible.builtin.script: files/scripts/detect-os.sh
  register: detect_os

- name: Set boostrap_os.
  ansible.builtin.set_fact:
    bootstrap_os: "{{ detect_os.stdout | regex_replace('GNU/Linux ','',ignorecase=True) | trim | lower }}"

- name: Set boostrap_distro & boostrap_version.
  ansible.builtin.set_fact:
    bootstrap_distro: "{{ (bootstrap_os | split(' '))[0] }}"
    bootstrap_version: "{{ (bootstrap_os | split(' '))[1] }}"

- name: Set bootstrap_os_family = debian.
  ansible.builtin.set_fact:
    bootstrap_os_family: "debian"
  when: bootstrap_distro in bootstrap_debian_family

- name: Set bootstrap_os_family = redhat.
  ansible.builtin.set_fact:
    bootstrap_os_family: "redhat"
  when: bootstrap_distro in bootstrap_redhat_family

- name: "Include {{ bootstrap_distro }} {{ bootstrap_version }} vars."
  ansible.builtin.include_vars:
    file: "{{ bootstrap_distro }}-{{ bootstrap_version }}.yml"

- ansible.builtin.include_tasks:
    file: "{{ bootstrap_os_family }}.yml"
