---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include hampusstrom.ansible_host_bootstrap"
      ansible.builtin.include_role:
        name: "hampusstrom.ansible_host_bootstrap"
